(() => {
"use strict";
const {canvas,ctx,$,keys,clamp,overlap}=window.EclipseCore;
$("versionLabel").textContent="Remastered v8.0 · Ruins of the Eclipse";
const ui={menu:$("menu"),pause:$("pause"),difficulty:$("difficulty"),hpBar:$("hpBar"),hpText:$("hpText"),stBar:$("stBar"),stText:$("stText"),xpBar:$("xpBar"),levelText:$("levelText"),bossBar:$("bossBar"),bossPhase:$("bossPhase"),souls:$("souls"),deaths:$("deaths"),relics:$("relics"),combo:$("combo"),notice:$("notice"),continueGame:$("continueGame"),comboFlash:$("comboFlash")};
const WORLD=12400,GROUND=455,checkpoints=[120,2500,5200,7700,10100];
let mode="menu",difficulty="normal",souls=0,deaths=0,checkpoint=0,cameraX=0,last=0,relicCount=0,level=1,xp=0,nextXp=60,victory=false,assetsReady=false,noticeTimer=0,shake=0,comboCount=0,comboTimer=0,rainTime=0,quest=0,key=false;
const images={},sources={kael:"v7-kael.png",soldier:"v7-soldier.png",boss:"v7-boss.png",world1:"v7-world.png",tiles:"v7-tiles.png",items:"v7-items.png",world2:"v8-ruins-world.png",npc:"v8-npc.png",mini:"v8-mini-boss.png",chest:"v8-chest.png"};
const P={x:120,y:359,w:48,h:96,vx:0,vy:0,speed:285,jump:700,gravity:1900,onGround:false,baseHp:180,maxHp:180,hp:180,maxSt:120,st:120,facing:1,attack:0,attackCd:0,dodge:0,dodgeCd:0,block:0,inv:0,coyote:0,jumpBuffer:0,anim:0,skillCd:0,comboStep:0,comboWindow:0,baseDamage:38};
const platforms=[[0,455,1160,100],[1240,455,760,100],[2080,455,1080,100],[3240,455,720,100],[4040,455,1280,100],[5400,455,920,100],[6400,455,1150,100],[7630,455,2170,100],[9880,455,2520,100],[600,340,270,32],[1390,315,250,32],[1700,250,220,32],[2580,335,300,32],[3460,315,250,32],[4300,340,300,32],[4770,270,270,32],[5700,315,310,32],[6750,325,330,32],[8080,335,260,32],[8660,280,230,32],[10120,340,300,32],[10640,280,260,32],[11200,330,300,32],[11800,260,250,32]].map(a=>({x:a[0],y:a[1],w:a[2],h:a[3]}));
const enemies=[],particles=[],npcs=[{x:10040,y:359,w:64,h:96}],chests=[{x:10800,y:423,w:48,h:32,open:false,locked:false},{x:11680,y:423,w:48,h:32,open:false,locked:true}];
function loadAssets(done){let n=0,entries=Object.entries(sources);entries.forEach(([k,src])=>{let im=new Image();im.onload=()=>{images[k]=im;if(++n===entries.length){assetsReady=true;done()}};im.onerror=()=>notice("ERRORE ASSET: "+src);im.src=src})}
function enemy(x,type="soldier"){let boss=type==="boss",mini=type==="mini",hp=boss?(difficulty==="fractured"?1700:1180):mini?700:125;return{type,x,y:GROUND-(boss?144:mini?112:96),w:boss?96:mini?80:64,h:boss?144:mini?112:96,vx:0,vy:0,maxHp:hp,hp,damage:boss?28:mini?21:17,phase:1,dir:-1,attackCd:0,hurt:0,dead:false,onGround:false,anim:0}}
function reset(){enemies.length=0;[850,1530,2780,3550,4520,5860,6840,10350,10950,11650].forEach(x=>enemies.push(enemy(x)));enemies.push(enemy(9300,"boss"));enemies.push(enemy(12050,"mini"))}
function frag(){let loss=difficulty==="fractured"?Math.min(.7,deaths*.05):0;P.maxHp=Math.max(54,Math.round(P.baseHp*(1-loss)));P.hp=Math.min(P.hp||P.maxHp,P.maxHp)}
function save(){localStorage.setItem("eclipseV8",JSON.stringify({difficulty,souls,deaths,checkpoint,relicCount,level,xp,nextXp,quest,key}));ui.continueGame.disabled=false}
function load(){try{let d=JSON.parse(localStorage.getItem("eclipseV8")||"null");if(!d)return false;difficulty=d.difficulty||"normal";souls=d.souls||0;deaths=d.deaths||0;checkpoint=d.checkpoint||0;relicCount=d.relicCount||0;level=d.level||1;xp=d.xp||0;nextXp=d.nextXp||60;quest=d.quest||0;key=!!d.key;ui.difficulty.value=difficulty;frag();return true}catch{return false}}
function notice(t){ui.notice.textContent=t;ui.notice.classList.add("on");clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>ui.notice.classList.remove("on"),2200)}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*340,vy:(Math.random()-.8)*310,life:.5+Math.random()*.25,color,size:2+Math.random()*4})}
function solve(b,dt){b.onGround=false;b.x+=b.vx*dt;for(const p of platforms)if(overlap(b,p)){if(b.vx>0)b.x=p.x-b.w;else if(b.vx<0)b.x=p.x+p.w;b.vx=0}b.y+=b.vy*dt;for(const p of platforms)if(overlap(b,p)){if(b.vy>0){b.y=p.y-b.h;b.vy=0;b.onGround=true}else if(b.vy<0){b.y=p.y+p.h;b.vy=0}}}
function gainXp(a){xp+=a;while(xp>=nextXp){xp-=nextXp;level++;nextXp=Math.round(nextXp*1.3+18);P.baseDamage+=4;P.baseHp+=10;frag();notice("LIVELLO "+level)}}
function damage(n,x){if(P.inv>0||mode!=="play")return;if(P.block>0&&Math.sign(x-P.x)===P.facing){P.st=Math.max(0,P.st-20);notice("PARATA");return}P.hp-=n;P.inv=.8;P.vx=(P.x<x?-1:1)*360;P.vy=-280;shake=10;burst(P.x+30,P.y+45,"#c33b53",18);if(P.hp<=0)die()}
function kill(e){e.dead=true;souls+=e.type==="boss"?230:e.type==="mini"?110:12;gainXp(e.type==="boss"?230:e.type==="mini"?120:28);if(e.type==="mini"){key=true;quest=2;notice("CHIAVE DELLE ROVINE OTTENUTA");save()}}
function attack(){if(P.attackCd>0||mode!=="play")return;if(P.comboWindow>0)P.comboStep=(P.comboStep%3)+1;else P.comboStep=1;P.comboWindow=.55;P.attack=.3;P.attackCd=.3;let reach=[0,78,88,105][P.comboStep],base=[0,44,52,68][P.comboStep],hit={x:P.facing>0?P.x+P.w:P.x-reach,y:P.y+18,w:reach,h:68};enemies.forEach(e=>{if(e.dead||!overlap(hit,e))return;let dmg=e.type==="boss"?Math.round((base+P.baseDamage-38)*.75):e.type==="mini"?Math.round((base+P.baseDamage-38)*.85):base+P.baseDamage-38;e.hp-=dmg;e.hurt=.17;e.vx=P.facing*(190+P.comboStep*30);shake=P.comboStep===3?9:5;burst(e.x+e.w/2,e.y+e.h/2,"#72baff",14+P.comboStep*4);comboCount++;comboTimer=2;ui.comboFlash.querySelector("b").textContent=comboCount;ui.comboFlash.classList.add("on");if(e.hp<=0)kill(e)})}
function dodge(){if(P.dodgeCd>0||P.st<28||mode!=="play")return;P.dodge=.28;P.dodgeCd=.7;P.inv=.42;P.st-=28;P.vx=P.facing*700}
function block(){if(mode==="play"&&P.st>0){P.block=.2;P.vx*=.55}}
function skill(){if(P.skillCd>0||P.st<45||mode!=="play")return;P.skillCd=4.5;P.st-=45;shake=13;burst(P.x+30,P.y+44,"#75c7ff",40);let wave={x:P.x-170,y:P.y-100,w:390,h:250};enemies.forEach(e=>{if(!e.dead&&overlap(wave,e)){e.hp-=e.type==="boss"?60:e.type==="mini"?78:95;if(e.hp<=0)kill(e)}})}
function interact(){let npc=npcs.find(n=>Math.abs(P.x-n.x)<95);if(npc){if(quest===0){quest=1;notice("VEYL: Trova la Chiave delle Rovine.")}else if(quest===1)notice("VEYL: Il guardiano è oltre il santuario.");else if(quest===2)notice("VEYL: Apri lo scrigno sigillato.");else notice("VEYL: Le rovine ricordano il tuo nome.");save();return}let chest=chests.find(c=>!c.open&&Math.abs(P.x-c.x)<80);if(chest){if(chest.locked&&!key){notice("SERVE LA CHIAVE DELLE ROVINE");return}chest.open=true;if(chest.locked){P.baseDamage+=14;quest=3;relicCount++;notice("RUNA DEL SANTUARIO: +14 DANNO")}else{P.baseHp+=25;frag();notice("FRAMMENTO DI VITA: +25")}save()}}
function die(){if(mode!=="play")return;deaths++;frag();mode="dead";notice(difficulty==="fractured"?"FRAMMENTAZIONE: VITA MASSIMA -5%":"KAEL È CADUTO");setTimeout(()=>{Object.assign(P,{x:checkpoints[checkpoint],y:359,vx:0,vy:0,hp:P.maxHp,st:P.maxSt,inv:1.5});comboCount=0;reset();mode="play";save()},850)}
function start(cont=false){if(!assetsReady){notice("ATTENDI IL CARICAMENTO");return}if(cont){if(!load())return}else{difficulty=ui.difficulty.value;souls=0;deaths=0;checkpoint=0;relicCount=0;level=1;xp=0;nextXp=60;quest=0;key=false;Object.assign(P,{baseHp:180,maxHp:180,hp:180,maxSt:120,st:120,baseDamage:38})}victory=false;frag();Object.assign(P,{x:checkpoints[checkpoint],y:359,vx:0,vy:0,hp:P.maxHp,st:P.maxSt,inv:0,skillCd:0});reset();mode="play";ui.menu.classList.remove("visible");notice("CIMITERO DEL GIURAMENTO");save()}
function updateP(dt){let l=keys.has("ArrowLeft")||keys.has("KeyA"),r=keys.has("ArrowRight")||keys.has("KeyD"),m=(r?1:0)-(l?1:0);if(m)P.facing=m;if(P.dodge<=0&&P.block<=0)P.vx+=(m*P.speed-P.vx)*Math.min(1,dt*12);P.vy+=P.gravity*dt;P.coyote=P.onGround?.12:Math.max(0,P.coyote-dt);P.jumpBuffer=Math.max(0,P.jumpBuffer-dt);if(P.jumpBuffer>0&&P.coyote>0){P.vy=-P.jump;P.coyote=0;P.jumpBuffer=0}solve(P,dt);if(P.y>650)die();P.attack=Math.max(0,P.attack-dt);P.attackCd=Math.max(0,P.attackCd-dt);P.dodge=Math.max(0,P.dodge-dt);P.dodgeCd=Math.max(0,P.dodgeCd-dt);P.block=Math.max(0,P.block-dt);P.inv=Math.max(0,P.inv-dt);P.skillCd=Math.max(0,P.skillCd-dt);P.comboWindow=Math.max(0,P.comboWindow-dt);P.st=Math.min(P.maxSt,P.st+(P.block>0?8:30)*dt);P.anim+=dt;checkpoints.forEach((x,i)=>{if(i>checkpoint&&Math.abs(P.x-x)<80){checkpoint=i;notice("CHECKPOINT "+(i+1));save()}});cameraX+=((P.x-canvas.width*.4)-cameraX)*Math.min(1,dt*5.8);cameraX=clamp(cameraX,0,WORLD-canvas.width);comboTimer=Math.max(0,comboTimer-dt);if(comboTimer<=0){comboCount=0;ui.comboFlash.classList.remove("on")}}
function updateE(dt){enemies.forEach(e=>{if(e.dead)return;e.attackCd=Math.max(0,e.attackCd-dt);e.hurt=Math.max(0,e.hurt-dt);e.anim+=dt;let dist=P.x-e.x;if(e.type==="boss"||e.type==="mini"){let q=e.hp/e.maxHp;e.phase=difficulty==="fractured"?(q>.66?1:q>.33?2:3):(q>.5?1:2);e.dir=Math.sign(dist)||-1;let speeds=e.type==="boss"?[0,105,165,230]:[0,120,175,225];if(Math.abs(dist)>145)e.vx=e.dir*speeds[e.phase];else e.vx*=.8;if(e.attackCd<=0&&Math.abs(dist)<235){e.attackCd=[0,1.55,1.05,.7][e.phase];let reach=e.phase===3?275:205,hit={x:e.dir>0?e.x+e.w:e.x-reach,y:e.y+35,w:reach,h:100};if(overlap(hit,P))damage((e.type==="boss"?18:15)+e.phase*7,e.x)}}else{if(Math.abs(dist)<620){e.dir=Math.sign(dist)||e.dir;e.vx=e.dir*95}else e.vx*=.82;if(Math.abs(dist)<78&&e.attackCd<=0){e.attackCd=1.1;damage(e.damage,e.x)}}e.vy+=1750*dt;solve(e,dt)})}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=600*dt}}
function drawP(){if(P.inv>0&&Math.floor(P.inv*12)%2===0)return;let f=0;if(Math.abs(P.vx)>25)f=2+(Math.floor(P.anim*8)%2);if(!P.onGround)f=P.vy<0?4:5;if(P.attack>0)f=[0,6,7,8][P.comboStep]||6;if(P.dodge>0)f=9;if(P.block>0)f=10;if(P.skillCd>4.1)f=11;ctx.save();ctx.translate(P.x+32,P.y);ctx.scale(P.facing,1);ctx.drawImage(images.kael,f*64,0,64,96,-32,0,64,96);ctx.restore()}
function drawE(e){if(e.hurt>0)ctx.globalAlpha=.5;if(e.type==="boss")ctx.drawImage(images.boss,(e.phase-1)*96,0,96,144,e.x,e.y,96,144);else if(e.type==="mini")ctx.drawImage(images.mini,(e.phase-1)*80,0,80,112,e.x,e.y,80,112);else{let f=Math.floor(e.anim*6)%4;ctx.drawImage(images.soldier,f*64,0,64,96,e.x,e.y,64,96)}ctx.globalAlpha=1}
function drawRain(){ctx.strokeStyle="rgba(180,210,225,.20)";for(let i=0;i<90;i++){let x=(i*137+rainTime*360)%1020-30,y=(i*83+rainTime*620)%580-20;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+14);ctx.stroke()}}
function draw(){ctx.drawImage(P.x<9800?images.world1:images.world2,0,0,960,540);drawRain();ctx.save();ctx.translate(-cameraX,0);platforms.forEach((p,i)=>{let tx=(i%8)*16;for(let x=p.x;x<p.x+p.w;x+=16)for(let y=p.y;y<p.y+p.h;y+=16)ctx.drawImage(images.tiles,tx,0,16,16,x,y,16,16)});npcs.forEach(n=>{let f=Math.floor(performance.now()/300)%4;ctx.drawImage(images.npc,f*64,0,64,96,n.x,n.y,64,96)});chests.forEach(c=>ctx.drawImage(images.chest,c.open?48:0,0,48,32,c.x,c.y,48,32));enemies.forEach(e=>{if(!e.dead)drawE(e)});drawP();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.globalAlpha=1;ctx.restore();ctx.fillStyle="rgba(5,7,11,.72)";ctx.fillRect(18,18,250,36);ctx.fillStyle="#e9e1d8";ctx.font="16px Georgia";ctx.fillText(P.x<9800?"Cimitero del Giuramento":"Rovine dell'Eclissi",32,42);if(P.x>9900&&P.x<10200){ctx.fillStyle="rgba(5,7,11,.82)";ctx.fillRect(330,460,300,42);ctx.fillStyle="#f1e9df";ctx.textAlign="center";ctx.fillText("Premi E per parlare",480,487);ctx.textAlign="left"}}
function hud(){ui.hpBar.style.width=P.hp/P.maxHp*100+"%";ui.hpText.textContent=Math.ceil(P.hp)+"/"+P.maxHp;ui.stBar.style.width=P.st/P.maxSt*100+"%";ui.stText.textContent=Math.ceil(P.st)+"/"+P.maxSt;ui.xpBar.style.width=xp/nextXp*100+"%";ui.levelText.textContent="Lv. "+level;ui.souls.textContent=souls;ui.deaths.textContent=deaths;ui.relics.textContent=relicCount;ui.combo.textContent=comboCount;let b=enemies.find(e=>(e.type==="boss"||e.type==="mini")&&!e.dead&&Math.abs(P.x-e.x)<900);if(b){ui.bossBar.style.width=b.hp/b.maxHp*100+"%";ui.bossPhase.textContent=(b.type==="mini"?"Guardiano · ":"Custode · ")+"Fase "+b.phase+"/"+(difficulty==="fractured"?3:2)}else{ui.bossBar.style.width="0%";ui.bossPhase.textContent="—"}}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;rainTime+=dt;if(!assetsReady){ctx.fillStyle="#06080c";ctx.fillRect(0,0,960,540);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.fillText("Caricamento v8.0...",480,270);requestAnimationFrame(loop);return}if(mode==="play"){updateP(dt);updateE(dt);updateParticles(dt);hud()}draw();requestAnimationFrame(loop)}
function press(k){keys.add(k);if(k==="Space")P.jumpBuffer=.12;if(k==="KeyJ")attack();if(k==="KeyK")dodge();if(k==="KeyL")block();if(k==="KeyQ")skill();if(k==="KeyE")interact();if(k==="KeyP"){if(mode==="play"){mode="pause";ui.pause.classList.add("visible")}else if(mode==="pause"){mode="play";ui.pause.classList.remove("visible")}}}
addEventListener("keydown",e=>{if(["Space","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();press(e.code)});addEventListener("keyup",e=>keys.delete(e.code));
document.querySelectorAll(".mobile button").forEach(b=>{let k=b.dataset.key;b.addEventListener("pointerdown",e=>{e.preventDefault();b.setPointerCapture(e.pointerId);press(k)});b.addEventListener("pointerup",()=>keys.delete(k));b.addEventListener("pointercancel",()=>keys.delete(k))});
$("newGame").onclick=()=>start(false);$("continueGame").onclick=()=>start(true);$("resume").onclick=()=>{mode="play";ui.pause.classList.remove("visible")};$("quit").onclick=()=>{save();mode="menu";ui.pause.classList.remove("visible");ui.menu.classList.add("visible")};
ui.continueGame.disabled=!localStorage.getItem("eclipseV8");reset();frag();hud();loadAssets(()=>notice("PROJECT ECLIPSE v8.0 PRONTO"));requestAnimationFrame(loop);
})();